const WATCHLIST = [
  {
    id: "opus-2025",
    title: "Opus",
    type: "movie",
    year: 2025,
    vibe: "Stylized thriller",
    intensity: "messy",
    adjectives: ["slick", "arty", "offbeat"],
    hint: "young writer enters orbit of a legendary pop figure; ambition, performance, and something off underneath",
    nostalgic: false,
    featured: true,
    watched: false,
    rating: null,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "opus"
  },
  {
    id: "forbidden-fruits-2026",
    title: "Forbidden Fruits",
    type: "movie",
    year: 2026,
    vibe: "Dark feminine",
    intensity: "messy",
    adjectives: ["stylized", "seductive", "gorey"],
    hint: "four girls, one secret; forbidden desire, tension, and glossy danger",
    nostalgic: false,
    featured: true,
    watched: false,
    rating: null,
    review: "",
    poster: "posters/forbidden-fruits.jpg",
    autoPoster: false,
    watchSlug: ""
  },
  {
    id: "bodies-bodies-bodies-2022",
    title: "Bodies Bodies Bodies",
    type: "movie",
    year: 2022,
    vibe: "Chaotic satire",
    intensity: "messy",
    adjectives: ["campy", "neon", "petty"],
    hint: "wealthy young friends turn on each other during a party game; paranoia, ego, and stupidity spiral fast",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 4.0,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "bodies-bodies-bodies"
  },
  {
    id: "promising-young-woman-2020",
    title: "Promising Young Woman",
    type: "movie",
    year: 2020,
    vibe: "Dark feminine",
    intensity: "unwell",
    adjectives: ["sharp", "vengeful", "stylized"],
    hint: "woman weaponizes men’s expectations against them; grief, rage, and revenge in candy colors",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 4.5,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "promising-young-woman"
  },
  {
    id: "the-shining-1980",
    title: "The Shining",
    type: "movie",
    year: 1980,
    vibe: "Psychological horror",
    intensity: "unwell",
    adjectives: ["iconic", "cold", "unraveling"],
    hint: "family isolates in empty hotel for winter; cabin fever, haunting, and madness take over",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 4.5,
    review: "",
    poster: "",
    autoPoster: true, 
    watchSlug: "the-shining"
  },
  {
    id: "the-substance-2024",
    title: "The Substance",
    type: "movie",
    year: 2024,
    vibe: "Body horror",
    intensity: "unwell",
    adjectives: ["grotesque", "feminine", "extreme"],
    hint: "aging and desirability are pushed through a body-horror experiment; vanity, identity, and violence explode",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 4.5,
    review: "",
    poster: "",
    autoPoster: true, 
    watchSlug: "the-substance"
  },
  {
    id: "hustlers-2019",
    title: "Hustlers",
    type: "movie",
    year: 2019,
    vibe: "Crime / glam",
    intensity: "messy",
    adjectives: ["glossy", "fun", "hustler-core"],
    hint: "strippers turn the tables on wealthy clients; friendship, survival, and luxury scams",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 4.0,
    review: "",
    poster: "posters/hustlers.jpg",
    autoPoster: false,
    watchSlug: "hustlers"
  },

  {
    id: "severance-2022",
    title: "Severance",
    type: "show",
    year: 2022,
    vibe: "Mind-bending sci-fi",
    intensity: "unwell",
    adjectives: ["corporate", "eerie", "clean"],
    hint: "employees split their consciousness between work and life; sterile office horror with identity rot",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 5.0,
    review: "",
    poster: "posters/severance.jpg",
    autoPoster: false,
    watchSlug: "severance"
  },
  {
    id: "fleabag-2016",
    title: "Fleabag",
    type: "show",
    year: 2016,
    vibe: "Dark comedy",
    intensity: "messy",
    adjectives: ["witty", "raw", "self-destructive"],
    hint: "woman self-sabotages her way through grief and desire; hilarious, intimate, and brutal underneath",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 5.0,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "fleabag"
  },

  {
    id: "nana-2006",
    title: "Nana",
    type: "anime",
    year: 2006,
    vibe: "Emotional / character drama",
    intensity: "unwell",
    adjectives: ["romantic", "messy", "devastating"],
    hint: "two women named Nana build their lives side by side; love, ambition, friendship, and heartbreak",
    nostalgic: false,
    featured: true,
    watched: true,
    rating: 5.0,
    review: "",
    poster: "posters/nana.jpg",
    autoPoster: false,
    watchSlug: "nana"
  },

  {
    id: "black-swan-2010",
    title: "Black Swan",
    type: "movie",
    year: 2010,
    vibe: "Dark feminine",
    intensity: "unwell",
    adjectives: ["obsessive", "beautiful", "unwell"],
    hint: "ballerina spirals into obsession and identity breakdown; perfection turns violent",
    nostalgic: false,
    featured: false,
    watched: false,
    rating: null,
    review: "",
    poster: "posters/black-swan.jpg",
    autoPoster: false,
    watchSlug: "black-swan"
  },
  {
    id: "the-handmaiden-2016",
    title: "The Handmaiden",
    type: "movie",
    year: 2016,
    vibe: "Erotic thriller",
    intensity: "unwell",
    adjectives: ["lush", "twisty", "dangerous"],
    hint: "con, romance, and betrayal fold into each other; layered manipulation and desire",
    nostalgic: false,
    featured: false,
    watched: false,
    rating: null,
    review: "",
    poster: "posters/the-handmaiden.jpg",
    autoPoster: false,
    watchSlug: "the-handmaiden"
  },
  {
    id: "portrait-of-a-lady-on-fire-2019",
    title: "Portrait of a Lady on Fire",
    type: "movie",
    year: 2019,
    vibe: "Queer romance",
    intensity: "messy",
    adjectives: ["aching", "elegant", "slow-burn"],
    hint: "artist and subject fall in love in isolation; intimacy, memory, and restraint",
    nostalgic: false,
    featured: false,
    watched: false,
    rating: null,
    review: "",
    poster: "posters/portrait-of-a-lady-on-fire.jpg",
    autoPoster: false,
    watchSlug: "portrait-of-a-lady-on-fire"
  },
  {
    id: "dark-2017",
    title: "Dark",
    type: "show",
    year: 2017,
    vibe: "Mind-bending sci-fi",
    intensity: "unwell",
    adjectives: ["dense", "bleak", "smart"],
    hint: "missing children expose a massive knot of time loops; family secrets and cosmic despair",
    nostalgic: false,
    featured: false,
    watched: false,
    rating: null,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "dark"
  },
  {
    id: "ergo-proxy-2006",
    title: "Ergo Proxy",
    type: "anime",
    year: 2006,
    vibe: "Psychological / philosophical",
    intensity: "unwell",
    adjectives: ["cold", "cerebral", "atmospheric"],
    hint: "post-apocalyptic mystery about consciousness and identity; androids, godhood, and decay",
    nostalgic: false,
    featured: false,
    watched: false,
    rating: null,
    review: "",
    poster: "posters/ergo-proxy.jpg",
    autoPoster: false,
    watchSlug: "ergo-proxy"
  },
  {
    id: "wild-child-2008",
    title: "Wild Child",
    type: "movie",
    year: 2008,
    vibe: "Teen chaos",
    intensity: "glossy",
    adjectives: ["cute", "bratty", "sleepover-core"],
    hint: "spoiled teen gets shipped off to boarding school; rebellion, makeover, and soft growth",
    nostalgic: true,
    featured: false,
    watched: true,
    rating: 3.5,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "wild-child"
  },
  {
    id: "shes-the-man-2006",
    title: "She’s the Man",
    type: "movie",
    year: 2006,
    vibe: "Teen comedy",
    intensity: "glossy",
    adjectives: ["chaotic", "silly", "iconic"],
    hint: "girl impersonates her twin brother to play soccer; disguises, romance, and dumb perfection",
    nostalgic: true,
    featured: false,
    watched: true,
    rating: 4.0,
    review: "",
    poster: "",
    autoPoster: true,
    watchSlug: "shes-the-man"
  },

]; 